# Some edits may cause bugs to defaults.
general:
# You can edit the prefix that may be shown in zac message or on notify message
 
   prefix: '&5&lzAC &7'
   appeal: '&3www.github.com/darkkiller9'
# Autoban
autoban: true